version: 1.0.{build}
image: Visual Studio 2019
clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%

    git checkout -qf %APPVEYOR_REPO_COMMIT%

    git submodule update --init --recursive
environment:
  NugetKey:
    secure: +YcuaW7ovBb8D6IGRkblmWICYLfHjM9c//eIBZTIVpSpsUO0qiQhHFdRq6mdrjT/
  CoverallRepoToken:
    secure: HqQcWcyK3uek+CLQdvrp7PcnQf+xTlxf2ImXDqDcmWjK8a9A7L62xYc9l9DsKdeu
  BotToken:
    secure: ujKq1K2ERj3dWA9hFatWJFa2lY0fYf+oCjGAMlvLF+7QC3/yyHzA0rsketX3dMaq
build_script:
- ps: .\build.ps1 -branch $env:APPVEYOR_REPO_BRANCH -buildCounter $env:APPVEYOR_BUILD_NUMBER -gitHash $env:APPVEYOR_REPO_COMMIT -commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE
test: off